#!/usr/bin/env gxi
;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;;
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

(import (only-in :std/build-script defbuild-script))

(defbuild-script
  '("types"
    "object-family/funcs"
    "object-family/indexed"
    "object-family/syntax"
    "object-family/interface"
    "extension-graph/support/data"
    "extension-graph/support/node-operations"
    "extension-graph/support/operation"
    "extension-graph/support/apply"
    "extension-graph/interface"
    "contribution/objects"
    "contribution/verification"
    "module-system/schema/support/contracts"
    "module-system/schema/support/slot-policy"
    "module-system/schema/support/field-resolution"
    "module-system/schema/support/object-slots"
    "module-system/schema/support/object"
    "module-system/schema/interface"
    "module-system/schema/slot-contracts"
    "module-system/schema/relations"
    "module-system/schema/validation"
    "module-system/types"
    "module-system/objects"
    "module-system/config"
    "module-system/graph/funs"
    "module-system/source/objects"
    "module-system/funs"
    "module-system/loader/objects"
    "module-system/loader/load-path"
    "module-system/catalog/objects"
    "module-system/projection/option-objects"
    "module-system/projection/option-validation"
    "profile-composition/bindings"
    "profile-composition/profile-bundle"
    "profile-composition/selection-syntax"
    "module-system/observability/diagnostics"
    "composition/lineage"
    "observability/types"
    "observability/funcs"
    "observability/objects"
    "observability/slot-debug"
    "observability/slot-presentation"
    "observability/debug"
    "observability/output"
    "observability/testing-case"
    "poo-clos/types"
    "poo-clos/objects"
    "poo-clos/funcs"
    "poo-clos/lambda-list"
    "poo-clos/method-combination"
    "poo-clos/classes"
    "poo-clos/model"
    "poo-clos/instance-state"
    "poo-clos/lifecycle"
    "poo-clos/dispatch"
    "poo-clos/evolution"
    "poo-clos/generic-evolution"
    "poo-clos/reflection"
    "poo-clos/load-form"
    "poo-clos/mop"
    "poo-clos/declaration-ir-core"
    "poo-clos/class-declaration-ir"
    "poo-clos/method-combination-declaration-ir"
    "poo-clos/declaration-ir"
    "poo-clos/syntax"
    "poo-clos/interface"))
